# -*- coding: utf-8 -*-
"""Desafio_Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1grDdQl5yb9__g80xjck9795mQ3DjFooS
"""

!pip install flask flask-ngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as rk


app = Flask(__name__) #the name of the application package
run_with_ngrok(app)


documento_joao = {
    "nome": "João",
    "cpf": "12345678900",
    "endereco": "Rua A",
    "contas": [
        {"agencia": "001", "numero": 1, "saldo": 1000},
        {"agencia": "001", "numero": 2, "saldo": 500}
    ]
}

@app.route("/") #code to assign HomePage URL in our app to function home.

def home():
  '''
  The entire line below must be written in a single line.
  '''
  return "<marquee><h3> TO CHECK IN PUT ADD '/input' TO THE URL AND TO CHECK OUT PUT ADD '/output' TO THE URL.</h3></marquee>"

@app.route("/input") #code to assign Input URL in our app to function input.

def input():
  return jsonify(documento_joao) # "documento_joao" is the dictionary we defined

@app.route('/output_data', methods=['GET', 'POST'])
def output_data_endpoint():
    pred = rk.choice(["positive", "negative"])
    nd = documento_joao
    nd["prediction"] = pred
    return jsonify(nd)

if __name__ == '__main__':
    app.run()

!apt-get install -y git